# Generated by Django 3.0.7 on 2020-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winemaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.CharField(blank=True, max_length=400)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('avg_yields_per_year_btl', models.IntegerField(blank=True)),
            ],
        ),
    ]
