# Generated by Django 3.0.7 on 2020-06-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('winemakers', '0001_initial'),
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=20)),
                ('grape_varieties', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='winemakers.Winemaker')),
                ('style', models.ManyToManyField(related_name='style', to='styles.Style')),
            ],
        ),
    ]
