# Generated by Django 3.0.7 on 2020-06-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winemakers', '0001_initial'),
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='winemaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winemakers', to='winemakers.Winemaker'),
        ),
    ]
