# Generated by Django 3.0.7 on 2020-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
