# Generated by Django 3.0.7 on 2020-06-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winemakers', '0001_initial'),
        ('wines', '0002_auto_20200606_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='winemaker',
        ),
        migrations.AddField(
            model_name='wine',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='winemakers.Winemaker'),
            preserve_default=False,
        ),
    ]
