# Generated by Django 3.0.7 on 2020-06-08 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wines', '0002_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='wine_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
