# Generated by Django 3.0.7 on 2020-06-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('wines', '0004_auto_20200608_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='style',
            field=models.ManyToManyField(blank=True, related_name='style', to='styles.Style'),
        ),
    ]
