# Generated by Django 3.0.7 on 2020-06-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('wines', '0005_wine_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='style',
            field=models.ManyToManyField(related_name='style', to='styles.Style'),
        ),
    ]
